services:
  ipfs:
    image: ipfs/kubo:latest
    restart: unless-stopped
    volumes:
      - ipfs_data:/data/ipfs
    environment:
      - IPFS_PATH=/data/ipfs
    ports:
      - 4001:4001/tcp
      - 4001:4001/udp
      # Admin panel, shouldn't be exposed to the internet
      - 127.0.0.1:5001:5001
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 1337:1337
    volumes:
      - ./src:/usr/src
volumes:
  ipfs_data:
