services:
  # IPFS
  ipfs-development:
    image: ipfs/kubo:latest
    restart: unless-stopped
    volumes:
      - ipfs_data:/data/ipfs
    environment:
      - IPFS_PATH=/data/ipfs
    ports:
      - 4001:4001/tcp
      - 4001:4001/udp
      # Admin panel, shouldn't be exposed to the internet
      - 127.0.0.1:5001:5001
    profiles:
      - development
  ipfs-production:
    image: ipfs/kubo:latest
    restart: unless-stopped
    volumes:
      - ipfs_data:/data/ipfs
    environment:
      - IPFS_PATH=/data/ipfs
    ports:
      - 4001:4001/tcp
      - 4001:4001/udp
    profiles:
      - production
      - production-no-dns
  # Backend
  backend-development:
    build:
      context: .
      dockerfile: Dockerfile.backend.development
    restart: unless-stopped
    ports:
      - 1337:1337
    volumes:
      - ./src:/usr/src
    depends_on:
      - ipfs-development
    environment:
      - ENVIRONMENT=development
    profiles:
      - development
  backend-production:
    build:
      context: .
      dockerfile: Dockerfile.backend.production
    restart: unless-stopped
    depends_on:
      - ipfs-production
    environment:
      - ENVIRONMENT=production
    profiles:
      - production
      - production-no-dns
  # Reverse proxy
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    command: 'caddy reverse-proxy --from ${DOMAIN} --to http://backend:1337'
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy_data:/data
      - caddy_conf:/config
    depends_on:
      - backend-production
    profiles:
      - production
  localtunnel:
    image: defunctzombie/localtunnel-server:latest
    restart: unless-stopped
    command: ['--port', '1337', '--local-host', 'backend']
    depends_on:
      - backend-production
    profiles:
      - production-no-dns

volumes:
  ipfs_data:
  caddy_data:
  caddy_conf:
